---
title: "MIA-NICE Sensitivity Analyses"
output: html_notebook
---

### 1. MIA-NICE Sensitivity Analyses
#### 1.1. Model 3
##### 1.1.1. Original ordering
```{r}
d_mia <- d_2014_selected %>%
  mutate(
    sex = ifelse( sex == "Female", 1, 0 ),
    Y = identity_change )

summary( d_mia )
table( d_mia$sex )
table( d_mia$Y )
nrow( d_mia )

# modeled auxiliary variables: age, sex, country of birth
set.seed( 123 )
mia_model_3 <- mia( data = d_mia,
                    X_names = c( "sexual_identity_2014" ), 
                    X_values_1 = c( "Non-heterosexual" ),
                    X_values_2 = c( "Heterosexual" ),
                    contrast_type = "ratio",
                    Y_model = Y ~ sexual_identity_2014 + age + sex + country_of_birth,
                    W_model = list(
                      sex ~ sexual_identity_2014,
                      age ~ sexual_identity_2014 + sex,
                      country_of_birth ~ sexual_identity_2014 + sex + age
                      ) )
mia_model_3

set.seed( 123 )
mia_model_3_ci <- get_CI( mia_model_3, n_boot = 1000, type = 'perc' )
mia_model_3_ci

results_mia_model_3 <- data.frame(
  estimate = round( mia_model_3$contrast_est, 2 ),
  lower_ci = round( mia_model_3_ci$ci_contrast$percent[4], 2 ),
  upper_ci = round( mia_model_3_ci$ci_contrast$percent[5], 2 ) ) %>%
  mutate( model = "mia_model_3",
          sample_size = nrow( d_mia ) )
results_mia_model_3

# diagnostic plots
class( mia_model_3$fit_Y )
lapply( mia_model_3$fit_W, class )
```

```{r}
plot( mia_model_3$fit_Y )
```

```{r}
plot( mia_model_3$fit_W[[1]] )
```

```{r}
plot( mia_model_3$fit_W[[2]] )
```

##### 1.1.2. Reverse ordering
```{r}
set.seed( 123 )
mia_model_check_3 <- mia( data = d_mia,
                          X_names = c( "sexual_identity_2014" ),
                          X_values_1 = c( "Non-heterosexual" ),
                          X_values_2 = c( "Heterosexual" ),
                          contrast_type = "ratio",
                          Y_model = Y ~ sexual_identity_2014 + age + sex + country_of_birth,
                          W_model = list(
                            country_of_birth ~ sexual_identity_2014,
                            age ~ sexual_identity_2014 + country_of_birth,
                            sex ~ sexual_identity_2014 + country_of_birth + age
                            ) )
mia_model_check_3

set.seed( 123 )
mia_model_check_3_ci <- get_CI( mia_model_check_3, n_boot = 1000, type = 'perc' )
mia_model_check_3_ci

results_mia_model_check_3 <- data.frame(
  estimate = round( mia_model_check_3$contrast_est, 2 ),
  lower_ci = round( mia_model_check_3_ci$ci_contrast$percent[4], 2 ),
  upper_ci = round( mia_model_check_3_ci$ci_contrast$percent[5], 2 ) ) %>%
  mutate( model = "mia_model_check_3",
          sample_size = nrow( d_mia ) )
results_mia_model_check_3
```

#### 1.2. Model 4
##### 1.2.1. Original ordering
```{r}
# modeled auxiliary variables: age, sex, country of birth, occupation
set.seed( 123 )
mia_model_4 <- mia( data = d_mia,
                    X_names = c( "sexual_identity_2014" ), 
                    X_values_1 = c( "Non-heterosexual" ),
                    X_values_2 = c( "Heterosexual" ),
                    contrast_type = "ratio",
                    Y_model = Y ~ sexual_identity_2014 + age + sex + country_of_birth + occupation,
                    W_model = list(
                      sex ~ sexual_identity_2014,
                      age ~ sexual_identity_2014 + sex,
                      country_of_birth ~ sexual_identity_2014 + sex + age,
                      occupation ~ sexual_identity_2014 + sex + age + country_of_birth
                      ) )
mia_model_4

set.seed( 123 )
mia_model_4_ci <- get_CI( mia_model_4, n_boot = 1000, type = 'perc' )
mia_model_4_ci

results_mia_model_4 <- data.frame(
  estimate = round( mia_model_4$contrast_est, 2 ),
  lower_ci = round( mia_model_4_ci$ci_contrast$percent[4], 2 ),
  upper_ci = round( mia_model_4_ci$ci_contrast$percent[5], 2 ) ) %>%
  mutate( model = "mia_model_4",
          sample_size = nrow( d_mia ) )
results_mia_model_4

# diagnostic plots
class( mia_model_4$fit_Y )
lapply( mia_model_4$fit_W, class )
```

```{r}
plot( mia_model_4$fit_Y )
```

```{r}
plot( mia_model_4$fit_W[[1]] )
```

```{r}
plot( mia_model_4$fit_W[[2]] )
```

##### 1.2.2. Reverse ordering
```{r}
set.seed( 123 )
mia_model_check_4 <- mia( data = d_mia,
                          X_names = c( "sexual_identity_2014" ),
                          X_values_1 = c( "Non-heterosexual" ),
                          X_values_2 = c( "Heterosexual" ),
                          contrast_type = "ratio",
                          Y_model = Y ~ sexual_identity_2014 + age + sex + country_of_birth + occupation,
                          W_model = list(
                            occupation ~ sexual_identity_2014,
                            country_of_birth ~ sexual_identity_2014 + occupation,
                            age ~ sexual_identity_2014 + occupation + country_of_birth,
                            sex ~ sexual_identity_2014 + occupation + country_of_birth + age
                            ) )
mia_model_check_4

set.seed( 123 )
mia_model_check_4_ci <- get_CI( mia_model_check_4, n_boot = 1000, type = 'perc' )
mia_model_check_4_ci

results_mia_model_check_4 <- data.frame(
  estimate = round( mia_model_check_4$contrast_est, 2 ),
  lower_ci = round( mia_model_check_4_ci$ci_contrast$percent[4], 2 ),
  upper_ci = round( mia_model_check_4_ci$ci_contrast$percent[5], 2 ) ) %>%
  mutate( model = "mia_model_check_4",
          sample_size = nrow( d_mia ) )
results_mia_model_check_4
```

#### 1.3. Plotting
```{r}
results_model_check <- bind_rows( 
  results_mia_model_3,
  results_mia_model_check_3,
  results_mia_model_4,
  results_mia_model_check_4
  )

#writexl::write_xlsx( results_model_check, "results_model_check.xlsx" )
#results_model_check <- read_excel(here("results_model_check.xlsx"))

results_model_check <- results_model_check %>%
  select( model, estimate, lower_ci, upper_ci )

desired_order <- c( "mia_model_3", "mia_model_check_3", "mia_model_4", "mia_model_check_4" )
                    
results_model_check <- results_model_check %>%
  mutate( model = factor( model, levels = desired_order ) ) %>%
  arrange( model )

results_model_check <- results_model_check %>% 
  add_row( model = "Model 3", .before = 1 )

results_model_check <- results_model_check %>% 
  add_row( model = "Model 4", .before = 4 )

results_model_check$model[ results_model_check$model == "mia_model_3" ] <- paste0( "   ", "Original ordering" )
results_model_check$model[ results_model_check$model == "mia_model_check_3" ] <- paste0( "   ", "Reverse ordering" )
results_model_check$model[ results_model_check$model == "mia_model_4" ] <- paste0( "   ", "Original ordering" )
results_model_check$model[ results_model_check$model == "mia_model_check_4" ] <- paste0( "   ", "Reverse ordering" )

results_model_check <- results_model_check %>% 
  add_column( "risk_ratio" = paste0(
    sprintf( "%.2f", results_model_check$estimate ), " (", 
    sprintf( "%.2f", results_model_check$lower_ci ), ", ", 
    sprintf( "%.2f", results_model_check$upper_ci ), ")" ),
    .before = 2 )

results_model_check$risk_ratio <- ifelse( is.na( results_model_check$estimate ), "",
                                          results_model_check$risk_ratio )

results_model_check <- results_model_check %>% 
  add_column( `     ` = paste( rep( " ", 20 ) , collapse = " " ), .after = 5 )

results_model_check <- results_model_check %>%
  add_column( temp1 = " ", .before = 2 ) %>%
  add_column( temp2 = " ", .before = 7 )

names( results_model_check )[ names( results_model_check ) == "model" ] <- " "
names( results_model_check )[ names( results_model_check ) == "temp1" ] <- "  "
names( results_model_check )[ names( results_model_check ) == "risk_ratio" ] <- "   "
names( results_model_check )[ names( results_model_check ) == "temp2" ] <- "    "

tm <- forest_theme(
  base_size = 11,
  colhead = list( fg_params = list( fontsize = 11 ) ), 
  base_family = "Arial",
  ci_col = "#0072B2"
  )

p_check_rr <- forest(
  results_model_check[ , c( 1:3, 7, 8 ) ],
  
  est = results_model_check$estimate,
  lower = results_model_check$lower_ci,
  upper = results_model_check$upper_ci,
  
  ci_column = 5,
  sizes = 0.4,
  
  xlim = c( 8, 20 ),
  ticks_at = c( 8, 12, 16, 20 ),
  xlab = "Risk Ratio (95% CI)",
  theme = tm
)

p_check_rr <- edit_plot( 
  p_check_rr,
  row = c( 1, 4 ),
  col = 1,
  gp = gpar( fontface = "bold" )
  )

p_check_rr <- add_text(
  p_check_rr,
  text = "MIA-NICE",
  col = 1,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 11,
    fontfamily = "Arial"
  )
)

p_check_rr <- add_text(
  p_check_rr,
  text = "Risk Ratio (95% CI)",
  col = 3,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 11,
    fontfamily = "Arial"
  )
)

p_check_rr <- edit_plot(
  p_check_rr,
  row = 1:6, 
  which = "background",
  gp = gpar( fill = NA )
  )

p_check_rr <- add_border(
  p_check_rr,
  part = "header",
  row = 1,
  col = 1:4,
  where = "bottom",
  gp = gpar( lwd = 1 )
  )

p_check_rr <- add_border(
  p_check_rr,
  part = "body",
  row = 1:5,
  col = 1:4,
  where = "bottom",
  gp = gpar( lwd = 1, col = "lightgrey" )
  )

plot( p_check_rr )
#ggsave( "forest_plot_check.svg", plot = p_check_rr, width = 6, height = 5 )
```