---
title: "Sexual Identity Change, SPHC 2014 Followed Up Until 2021"
author: "Willi Zhang, Sean McGrath, Maya Mathur, Shaun Seaman, Ilya Shpitser"
email: willi.zhang@ki.se
output:
  html_document:
    self_contained: true
    toc: true
    number_sections: true
    df_print: paged
    theme: cosmo
editor_options:
  chunk_output_type: console
---

### 1. Load Packages
```{r message=FALSE, warning=FALSE}
library(ggplot2)
library(tidyverse)
library(naniar)
library(haven)
library(finalfit)
library(survey)
library(miapack)
library(mice)
library(mitools)
library(forestploter)
library(readxl)
library(here)
library(DHARMa)
```

### 2. SPHC 2014, followed up to 2021
```{r}
load('/Volumes/projects/LGBT Project data/d_2014.RData')

# sexual identity in 2014
table( d_2014$F14U90G82, useNA = "always" )
d_2014$sexual_identity_2014 <- factor( ifelse( d_2014$F14U90G82 == 1, "Heterosexual", "Non-heterosexual" ),
                                       levels = c( "Heterosexual", "Non-heterosexual" ) )
table( d_2014$sexual_identity_2014, useNA = "always" )

# sexual identity in 2021
table( d_2014$F21F91, useNA = "always" )
d_2014$sexual_identity_2021 <- factor( ifelse( d_2014$F21F91 == 1, "Heterosexual", "Non-heterosexual" ),
                                       levels = c( "Heterosexual", "Non-heterosexual" ) )
table( d_2014$sexual_identity_2021, useNA = "always" )

# change in sexual identity
d_2014$identity_change <- ifelse( d_2014$sexual_identity_2014 == d_2014$sexual_identity_2021, 0, 1 )
table( d_2014$identity_change, useNA = "always" )

# sex
table( d_2014$kon, useNA = "always" )
d_2014$sex <- factor( ifelse( d_2014$kon == 1, "Male", "Female" ),
                      levels = c( "Male", "Female" ) )
table( d_2014$sex, useNA = "always" )

# age
summary( d_2014$F14alder )
d_2014$age <- d_2014$F14alder
d_2014$age_group <- cut( d_2014$age,
                         breaks = c( min( d_2014$age ), 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, max( d_2014$age ) ),
                         right = FALSE,
                         include.lowest = TRUE )
table( d_2014$age_group )

# country of birth
table( d_2014$fodelseland, useNA = "always" )
d_2014$country_of_birth <- factor( ifelse( d_2014$fodelseland == "Sverige", "Sweden",
                                           ifelse( d_2014$fodelseland == "Europa", "Europe", "Outside Europe" ) ),
                                   levels = c( "Sweden", "Europe", "Outside Europe" ) )
table( d_2014$country_of_birth, useNA = "always" )

# occupation
table( d_2014$SSYK_kl, useNA = "always" )
d_2014$occupation <- factor(
  ifelse(
    d_2014$SSYK_kl == "Yrken inom byggverksamhet och tillverkning" |
      d_2014$SSYK_kl == "Yrken inom lantbruk, trädgård, skogsbruk och fiske" |
      d_2014$SSYK_kl == "Yrken inom maskinell tillverkning och transport m.m.",
    "Manual and field trades",
    ifelse(
      d_2014$SSYK_kl == "Service-, omsorgs- och försäljningsyrken" |
        d_2014$SSYK_kl == "Yrken inom administration och kundtjänst" |
        d_2014$SSYK_kl == "Yrken med krav på kortare utbildning eller introduktion",
      "Service and support",
      ifelse(
        d_2014$SSYK_kl == "Yrken med krav på fördjupad högskolekompetens" |
          d_2014$SSYK_kl == "Yrken med krav på högskolekompetens eller motsvarande" |
          d_2014$SSYK_kl == "Chefsyrken" |
          d_2014$SSYK_kl == "Militära yrken",
        "Expertise and leadership",
        NA
      )
    )
  ),
  levels = c(
    "Manual and field trades",
    "Service and support",
    "Expertise and leadership"
  )
)
table( d_2014$occupation, useNA = "always" )

# association of age and occupation
ggplot( d_2014 %>%
          filter( !is.na( occupation ) ),
        aes( x = age_group, fill = occupation ) ) +
  geom_bar( position = "fill" ) +
  scale_y_continuous( labels = scales::percent ) +
  labs(
    x = "Age Group",
    y = "Percentage",
    fill = "Occupation" ) +
  theme_classic()

ggplot( d_2014,
        aes( x = age_group, fill = is.na( occupation ) ) ) +
  geom_bar( position = "fill" ) +
  scale_y_continuous( labels = scales::percent ) +
  labs(
    x = "Age Group",
    y = "Percentage",
    fill = "Missingness of Occupation" ) +
  theme_classic()

# association of age and identity change
ggplot( d_2014 %>%
          filter( !is.na( identity_change ) ) %>%
          mutate( identity_change = as.factor( ifelse( identity_change == 1, "Yes", "No" ) ) ),
        aes( x = age_group, fill = identity_change ) ) +
  geom_bar( position = "fill" ) +
  scale_y_continuous( labels = scales::percent ) +
  labs(
    x = "Age Group",
    y = "Percentage",
    fill = "Identity Change" ) +
  theme_classic()

ggplot( d_2014,
        aes( x = age_group, fill = is.na( identity_change ) ) ) +
  geom_bar( position = "fill" ) +
  scale_y_continuous( labels = scales::percent ) +
  labs(
    x = "Age Group",
    y = "Percentage",
    fill = "Missingness of Identity Change" ) +
  theme_classic()


# define study sample
prop_miss( d_2014$sexual_identity_2014 )

d_2014_selected <- d_2014 %>% 
  select( "sexual_identity_2014", "sexual_identity_2021", "identity_change", "age", "sex", "country_of_birth", "occupation" ) %>%
  filter( age >= 25,
          age <= 60,
          !is.na( sexual_identity_2014 ) # remove missingness in sexual_identity_2014 
          )
summary( d_2014_selected )
nrow( d_2014_selected ) # 11,274
miss_var_summary( d_2014_selected )

# characteristics table
explanatory =  c( "age", "sex", "country_of_birth", "occupation", "sexual_identity_2014", "sexual_identity_2021" )
dependent = "identity_change"

d_2014_table <- d_2014_selected %>%
  mutate( identity_change = as.factor( ifelse( identity_change == 1, "Yes", "No" ) ) ) %>%
  summary_factorlist( dependent,
                      explanatory, 
                      na_include = TRUE,
                      na_include_dependent = TRUE, 
                      total_col = TRUE,
                      add_col_totals = TRUE,
                      column = TRUE )

d_2014_table

# correlation of sexual identity in 2014 and occupation
ggplot( d_2014_selected %>%
          filter( !is.na( occupation ) ),
        aes( x = sexual_identity_2014, fill = occupation ) ) +
  geom_bar( position = "fill" ) +
  scale_y_continuous( labels = scales::percent ) +
  labs( x = "Sexual Identity in 2014", y = "Percentage", fill = "Occupation" ) +
  theme_classic()

ggplot( d_2014_selected,
        aes( x = sexual_identity_2014, fill = is.na( occupation ) ) ) +
  geom_bar( position = "fill" ) +
  scale_y_continuous( labels = scales::percent ) +
  labs( x = "Sexual Identity in 2014", y = "Percentage", fill = "Missingness of Occupation" ) +
  theme_classic()

# correlation of sexual identity in 2014 and identity change
ggplot( d_2014_selected %>% 
          filter( !is.na( identity_change ) ) %>%
          mutate( identity_change = as.factor( ifelse( identity_change == 1, "Yes", "No" ) ) ),
        aes( x = sexual_identity_2014, fill = identity_change ) ) +
  geom_bar( position = "fill" ) +
  scale_y_continuous( labels = scales::percent ) +
  labs( x = "Sexual Identity in 2014", y = "Percentage", fill = "Identity Change" ) +
  theme_classic()

ggplot( d_2014_selected,
        aes( x = sexual_identity_2014, fill = is.na( identity_change ) ) ) +
  geom_bar( position = "fill" ) +
  scale_y_continuous( labels = scales::percent ) +
  labs( x = "Sexual Identity in 2014", y = "Percentage", fill = "Missingness of Identity Change" ) +
  theme_classic()

# correlation of occupation and identity change
ggplot( d_2014_selected %>%
          filter( !is.na( identity_change ) ) %>%
          mutate( occupation = fct_na_value_to_level( occupation, level = "Missing" ),
                  identity_change = as.factor( ifelse( identity_change == 1, "Yes", "No" ) ) ),
        aes( x = occupation, fill = identity_change ) ) +
  geom_bar( position = "fill" ) +
  scale_y_continuous( labels = scales::percent ) +
  labs( x = "Occupation", y = "Percentage", fill = "Identity Change" ) +
  theme_classic()

ggplot( d_2014_selected %>%
          mutate( occupation = fct_na_value_to_level( occupation, level = "Missing" ) ),
        aes( x = occupation, fill = is.na( identity_change ) ) ) +
  geom_bar( position = "fill" ) +
  scale_y_continuous( labels = scales::percent ) +
  labs( x = "Occupation", y = "Percentage", fill = "Missingness of Identity Change" ) +
  theme_classic()


### association (risk ratio) of occupation and identity change ###

# occupation and missingness of identity change
tab1 <- table( d_2014_selected$occupation, is.na( d_2014_selected$identity_change ) ) # among participants with complete occupation data
tab1

( tab1[ "Service and support", "TRUE" ] / sum( tab1[ "Service and support", ] ) ) / 
  ( tab1[ "Manual and field trades", "TRUE" ] / sum( tab1[ "Manual and field trades", ] ) ) # service and support vs manual and field trades

( tab1[ "Expertise and leadership", "TRUE" ] / sum( tab1[ "Expertise and leadership", ] ) ) / 
  ( tab1[ "Manual and field trades", "TRUE" ] / sum( tab1[ "Manual and field trades", ] ) ) # expertise and leadership vs manual and field trades

# occupation and identity change
tab2 <- table( d_2014_selected$occupation, d_2014_selected$identity_change )
tab2

( tab2[ "Service and support", "1" ] / sum( tab2[ "Service and support", ] ) ) / 
  ( tab2[ "Manual and field trades", "1" ] / sum( tab2[ "Manual and field trades", ] ) ) # service and support vs manual and field trades

( tab2[ "Expertise and leadership", "1" ] / sum( tab2[ "Expertise and leadership", ] ) ) / 
  ( tab2[ "Manual and field trades", "1" ] / sum( tab2[ "Manual and field trades", ] ) ) # expertise and leadership vs manual and field trades

# check missing data pattern
md.pattern( 
  d_2014 %>% # among all participants
    filter( !is.na( sexual_identity_2014 ) ) %>%
    select( "occupation", "sexual_identity_2021" ) %>%
    rename( SI_2021 = sexual_identity_2021 ),
  rotate.names = FALSE )

d_2014 %>%
  filter( !is.na( sexual_identity_2014 ) ) %>%
  summarise(
    prop_id2021_missing_given_occ_missing = mean( is.na( sexual_identity_2021[ is.na( occupation ) ] ) ),
    prop_occ_missing_given_id2021_missing = mean( is.na( occupation[ is.na( sexual_identity_2021 ) ] ) )
  )

pdf( "missing_pattern.pdf", width = 4, height = 6 )
md.pattern( d_2014_selected %>% # among 25-60 years
              select( "occupation", "sexual_identity_2021" ) %>%
              rename( SI_2021 = sexual_identity_2021 ),
            rotate.names = FALSE )
dev.off()

d_2014_selected %>%
  summarise(
    prop_id2021_missing_given_occ_missing = mean( is.na( sexual_identity_2021[ is.na( occupation ) ] ) ),
    prop_occ_missing_given_id2021_missing = mean( is.na( occupation[ is.na( sexual_identity_2021 ) ] ) )
  )
```

### 3. Complete-case analysis
```{r}
d_cc <- d_2014_selected %>% 
  select( sexual_identity_2014, identity_change ) %>%
  filter( !is.na( identity_change ) )
nrow( d_cc )
summary( d_cc )
table( d_cc$identity_change )

design <- svydesign( ids = ~ 1, data = d_cc ) # simple random sampling design
poisson_robust_model <- svyglm( identity_change ~ sexual_identity_2014,
                                design = design,
                                family = quasipoisson( link = "log" ) )

summary( poisson_robust_model )

results_cc <- round( 
  exp( cbind( coef( poisson_robust_model )[ 2 ],
              confint( poisson_robust_model ) [ 2, , drop = FALSE ] ) ), 2 ) %>% 
  as.data.frame() %>%
  remove_rownames() %>%
  mutate( model = "Complete-case analysis",
          sample_size = nrow( d_cc ) ) %>%
  rename(
    estimate = `V1`,
    lower_ci = `2.5 %`,
    upper_ci = `97.5 %`
  )
results_cc
```

### 4. MIA Method
#### 4.1. Model 2
```{r}
# modeled auxiliary variable: occupation

d_mia <- d_2014_selected %>%
  mutate(
    sex = ifelse( sex == "Female", 1, 0 ),
    Y = identity_change )

summary( d_mia )
table( d_mia$sex )
table( d_mia$Y )
nrow( d_mia )

# NICE
set.seed( 123 )
mia_nice_model_2 <- mia( 
  data = d_mia,
  X_names = "sexual_identity_2014",
  X_values_1 = "Non-heterosexual",
  X_values_2 = "Heterosexual",
  contrast_type = "ratio",
  Y_model = Y ~ sexual_identity_2014 * occupation,
  W_model = list(
    occupation ~ sexual_identity_2014 
    )
  )

mia_nice_model_2

set.seed( 123 )
mia_nice_model_2_ci <- get_CI( mia_nice_model_2, n_boot = 1000, type = 'perc' )
mia_nice_model_2_ci

results_mia_nice_model_2 <- data.frame(
  estimate = round( mia_nice_model_2$contrast_est, 2 ),
  lower_ci = round( mia_nice_model_2_ci$ci_contrast$percent[4], 2 ),
  upper_ci = round( mia_nice_model_2_ci$ci_contrast$percent[5], 2 ) ) %>%
  mutate( model = "mia_nice_model_2",
          sample_size = nrow( d_mia ) )
results_mia_nice_model_2


# ICE
mia_ice_model_2 <- mia_ice( 
  data = d_mia,
  X_names = "sexual_identity_2014",
  X_values_1 = "Non-heterosexual",
  X_values_2 = "Heterosexual",
  contrast_type = "ratio",
  Y_model = Y ~ sexual_identity_2014 * occupation,
  outer_model = g_hat ~ sexual_identity_2014 )

mia_ice_model_2

set.seed( 123 )
mia_ice_model_2_ci <- get_CI( mia_ice_model_2, n_boot = 1000, type = 'perc' )
mia_ice_model_2_ci

results_mia_ice_model_2 <- data.frame(
  estimate = round( mia_ice_model_2$contrast_est, 2 ),
  lower_ci = round( mia_ice_model_2_ci$ci_contrast$percent[4], 2 ),
  upper_ci = round( mia_ice_model_2_ci$ci_contrast$percent[5], 2 ) ) %>%
  mutate( model = "mia_ice_model_2",
          sample_size = nrow( d_mia ) )
results_mia_ice_model_2
```

#### 4.2. Model 3
```{r}
# modeled auxiliary variables: age, sex, country of birth

# NICE
set.seed( 123 )
mia_nice_model_3 <- mia( 
  data = d_mia,
  X_names = "sexual_identity_2014",
  X_values_1 = "Non-heterosexual",
  X_values_2 = "Heterosexual",
  contrast_type = "ratio",
  Y_model = Y ~ ( sexual_identity_2014 + age + sex + country_of_birth )^2,
  W_model = list(
    sex ~ sexual_identity_2014,
    age ~ sexual_identity_2014 + sex,
    country_of_birth ~ sexual_identity_2014 + sex + age
    )
  )

mia_nice_model_3

set.seed( 123 )
mia_nice_model_3_ci <- get_CI( mia_nice_model_3, n_boot = 1000, type = 'perc' )
mia_nice_model_3_ci

results_mia_nice_model_3 <- data.frame(
  estimate = round( mia_nice_model_3$contrast_est, 2 ),
  lower_ci = round( mia_nice_model_3_ci$ci_contrast$percent[4], 2 ),
  upper_ci = round( mia_nice_model_3_ci$ci_contrast$percent[5], 2 ) ) %>%
  mutate( model = "mia_nice_model_3",
          sample_size = nrow( d_mia ) )
results_mia_nice_model_3


# ICE
mia_ice_model_3 <- mia_ice( 
  data = d_mia,
  X_names = "sexual_identity_2014",
  X_values_1 = "Non-heterosexual",
  X_values_2 = "Heterosexual",
  contrast_type = "ratio",
  Y_model = Y ~ ( sexual_identity_2014 + age + sex + country_of_birth )^2,
  outer_model = g_hat ~ sexual_identity_2014 )

mia_ice_model_3

set.seed( 123 )
mia_ice_model_3_ci <- get_CI( mia_ice_model_3, n_boot = 1000, type = 'perc' )
mia_ice_model_3_ci

results_mia_ice_model_3 <- data.frame(
  estimate = round( mia_ice_model_3$contrast_est, 2 ),
  lower_ci = round( mia_ice_model_3_ci$ci_contrast$percent[4], 2 ),
  upper_ci = round( mia_ice_model_3_ci$ci_contrast$percent[5], 2 ) ) %>%
  mutate( model = "mia_ice_model_3",
          sample_size = nrow( d_mia ) )
results_mia_ice_model_3
```

#### 4.3. Model 4
```{r}
# modeled auxiliary variables: age, sex, country of birth, occupation

# NICE
set.seed( 123 )
mia_nice_model_4 <- mia( 
  data = d_mia,
  X_names = "sexual_identity_2014",
  X_values_1 = "Non-heterosexual",
  X_values_2 = "Heterosexual",
  contrast_type = "ratio",
  Y_model = Y ~ ( sexual_identity_2014 + age + sex + country_of_birth + occupation )^2,
  W_model = list(
    sex ~ sexual_identity_2014,
    age ~ sexual_identity_2014 + sex,
    country_of_birth ~ sexual_identity_2014 + sex + age,
    occupation ~ sexual_identity_2014 + sex + age + country_of_birth
    )
  )

mia_nice_model_4

set.seed( 123 )
mia_nice_model_4_ci <- get_CI( mia_nice_model_4, n_boot = 1000, type = 'perc' )
mia_nice_model_4_ci

results_mia_nice_model_4 <- data.frame(
  estimate = round( mia_nice_model_4$contrast_est, 2 ),
  lower_ci = round( mia_nice_model_4_ci$ci_contrast$percent[4], 2 ),
  upper_ci = round( mia_nice_model_4_ci$ci_contrast$percent[5], 2 ) ) %>%
  mutate( model = "mia_nice_model_4",
          sample_size = nrow( d_mia ) )
results_mia_nice_model_4


# ICE
mia_ice_model_4 <- mia_ice( 
  data = d_mia,
  X_names = "sexual_identity_2014",
  X_values_1 = "Non-heterosexual",
  X_values_2 = "Heterosexual",
  contrast_type = "ratio",
  Y_model = Y ~ ( sexual_identity_2014 + age + sex + country_of_birth + occupation )^2,
  outer_model = g_hat ~ sexual_identity_2014 )

mia_ice_model_4

set.seed( 123 )
mia_ice_model_4_ci <- get_CI( mia_ice_model_4, n_boot = 1000, type = 'perc' )
mia_ice_model_4_ci

results_mia_ice_model_4 <- data.frame(
  estimate = round( mia_ice_model_4$contrast_est, 2 ),
  lower_ci = round( mia_ice_model_4_ci$ci_contrast$percent[4], 2 ),
  upper_ci = round( mia_ice_model_4_ci$ci_contrast$percent[5], 2 ) ) %>%
  mutate( model = "mia_ice_model_4",
          sample_size = nrow( d_mia ) )
results_mia_ice_model_4
```

### 5. MICE
#### 5.1 Model 1
```{r}
# modeled auxiliary variable: sexual identity at T1

mi_dataset <- d_2014_selected %>% 
  select( sexual_identity_2014, identity_change ) %>%
  mutate( identity_change = as.factor( 
    ifelse( identity_change == 1, "Yes", "No" ) ) )

summary( mi_dataset )
str( mi_dataset )
miss_var_summary( mi_dataset )

mice_model_1 <- mice( mi_dataset, m = 50, seed = 123, print = FALSE )
summary( mice_model_1 )
plot( mice_model_1 )

imp_com <- complete( mice_model_1, action = "all", include = FALSE )
summary( imp_com$`1` )

imp_com <- lapply( imp_com, function( df ) {
  df %>%
    mutate( identity_change = ifelse( identity_change == "Yes", 1, 0 ) ) 
  } )
table( imp_com$`1`$identity_change )

design_imp <- svydesign( ids = ~ 1, data = imputationList( imp_com ) )

poisson_robust_model <- with( design_imp,
                              svyglm( identity_change ~ sexual_identity_2014, 
                                      family = quasipoisson( link = "log" ) ) )

pooled <- MIcombine( poisson_robust_model )
summary_result <- summary( pooled )
summary_result

results_mi_model_1 <- round( 
  exp( summary_result[ 2, c( 1, 3, 4 ) ] ),
  2 ) %>% 
  as.data.frame() %>%
  remove_rownames() %>%
  mutate( model = "mi_model_1",
          sample_size = nrow( mi_dataset ) ) %>%
  rename(
    estimate = "results",
    lower_ci = "(lower",
    upper_ci = "upper)"
  )
results_mi_model_1
```

#### 5.2. Model 2
```{r}
# modeled auxiliary variables: sexual identity at T1, occupation

mi_dataset <- d_2014_selected %>% 
  select( sexual_identity_2014, occupation, identity_change ) %>%
  mutate( identity_change = as.factor( 
    ifelse( identity_change == 1, "Yes", "No" ) ) )

summary( mi_dataset )
str( mi_dataset )
miss_var_summary( mi_dataset )

# add interactions
# wrote out all formulas explicitly for ease of review
form <- mice::make.formulas( mi_dataset )
form

form$sexual_identity_2014 <-
  sexual_identity_2014 ~ occupation + identity_change

form$occupation <-
  occupation ~ sexual_identity_2014 + identity_change

form$identity_change <-
  identity_change ~ sexual_identity_2014 * occupation

mice_model_2 <- mice( mi_dataset, formulas = form, m = 50, seed = 123, print = FALSE )
summary( mice_model_2 )
plot( mice_model_2 )

imp_com <- complete( mice_model_2, action = "all", include = FALSE )
summary( imp_com$`1` )

imp_com <- lapply( imp_com, function( df ) {
  df %>%
    mutate( identity_change = ifelse( identity_change == "Yes", 1, 0 ) ) 
  } )
table( imp_com$`1`$identity_change )

design_imp <- svydesign( ids = ~ 1, data = imputationList( imp_com ) )

poisson_robust_model <- with( design_imp,
                              svyglm( identity_change ~ sexual_identity_2014, 
                                      family = quasipoisson( link = "log" ) ) )

pooled <- MIcombine( poisson_robust_model )
summary_result <- summary( pooled )
summary_result

results_mi_model_2 <- round( 
  exp( summary_result[ 2, c( 1, 3, 4 ) ] ),
  2 ) %>% 
  as.data.frame() %>%
  remove_rownames() %>%
  mutate( model = "mi_model_2",
          sample_size = nrow( mi_dataset ) ) %>%
  rename(
    estimate = "results",
    lower_ci = "(lower",
    upper_ci = "upper)"
  )
results_mi_model_2
```

#### 5.3. Model 3
```{r}
# modeled auxiliary variables: sexual identity at T1, age, sex, country of birth

mi_dataset <- d_2014_selected %>% 
  select( sexual_identity_2014, identity_change, age, sex, country_of_birth ) %>%
  mutate( identity_change = as.factor( 
    ifelse( identity_change == 1, "Yes", "No" ) ) )

summary( mi_dataset )
str( mi_dataset )
miss_var_summary( mi_dataset )

# add interactions
# wrote out all formulas explicitly for ease of review
form <- mice::make.formulas( mi_dataset )
form

form$sexual_identity_2014 <-
  sexual_identity_2014 ~ identity_change + ( age + sex + country_of_birth )^2

form$identity_change <-
  identity_change ~ ( sexual_identity_2014 + age + sex + country_of_birth )^2

form$age <-
  age ~ identity_change + ( sexual_identity_2014 + sex + country_of_birth )^2

form$sex <-
  sex ~ identity_change + ( sexual_identity_2014 + age + country_of_birth )^2

form$country_of_birth <-
  country_of_birth ~ identity_change + ( sexual_identity_2014 + age + sex )^2

mice_model_3 <- mice( mi_dataset, m = 50, formulas = form, seed = 123, print = FALSE )
summary( mice_model_3 )
plot( mice_model_3 )

imp_com <- complete( mice_model_3, action = "all", include = FALSE )
summary( imp_com$`1` )

imp_com <- lapply( imp_com, function( df ) {
  df %>%
    mutate( identity_change = ifelse( identity_change == "Yes", 1, 0 ) ) 
  } )
table( imp_com$`1`$identity_change )

design_imp <- svydesign( ids = ~ 1, data = imputationList( imp_com ) )

poisson_robust_model <- with( design_imp,
                              svyglm( identity_change ~ sexual_identity_2014, 
                                      family = quasipoisson( link = "log" ) ) )

pooled <- MIcombine( poisson_robust_model )
summary_result <- summary( pooled )
summary_result

results_mi_model_3 <- round( 
  exp( summary_result[ 2, c( 1, 3, 4 ) ] ),
  2 ) %>% 
  as.data.frame() %>%
  remove_rownames() %>%
  mutate( model = "mi_model_3",
          sample_size = nrow( mi_dataset ) ) %>%
  rename(
    estimate = "results",
    lower_ci = "(lower",
    upper_ci = "upper)"
  )
results_mi_model_3
```

#### 5.4. Model 4
```{r}
# modeled auxiliary variables: sexual identity at T1, age, sex, country of birth, occupation

mi_dataset <- d_2014_selected %>% 
  select( sexual_identity_2014, identity_change, age, sex, country_of_birth, occupation ) %>%
  mutate( identity_change = as.factor( 
    ifelse( identity_change == 1, "Yes", "No" ) ) )

summary( mi_dataset )
str( mi_dataset )
miss_var_summary( mi_dataset )

# add interactions
# wrote out all formulas explicitly for ease of review
form <- mice::make.formulas( mi_dataset )
form

form$sexual_identity_2014 <-
  sexual_identity_2014 ~ identity_change + ( age + sex + country_of_birth + occupation )^2

form$identity_change <-
  identity_change ~ ( sexual_identity_2014 + age + sex + country_of_birth + occupation )^2

form$age <-
  age ~ identity_change + ( sexual_identity_2014 + sex + country_of_birth + occupation )^2

form$sex <-
  sex ~ identity_change + ( sexual_identity_2014 + age + country_of_birth + occupation )^2

form$country_of_birth <-
  country_of_birth ~ identity_change + ( sexual_identity_2014 + age + sex + occupation )^2

form$occupation <-
  occupation ~ identity_change + ( sexual_identity_2014 + age + sex + country_of_birth )^2

mice_model_4 <- mice( mi_dataset, m = 50, formulas = form, seed = 123, print = FALSE )
summary( mice_model_4 )
plot( mice_model_4 )

imp_com <- complete( mice_model_4, action = "all", include = FALSE )
summary( imp_com$`1` )

imp_com <- lapply( imp_com, function( df ) {
  df %>%
    mutate( identity_change = ifelse( identity_change == "Yes", 1, 0 ) ) 
  } )
table( imp_com$`1`$identity_change )

design_imp <- svydesign( ids = ~ 1, data = imputationList( imp_com ) )

poisson_robust_model <- with( design_imp,
                              svyglm( identity_change ~ sexual_identity_2014, 
                                      family = quasipoisson( link = "log" ) ) )

pooled <- MIcombine( poisson_robust_model )
summary_result <- summary( pooled )
summary_result

results_mi_model_4 <- round( 
  exp( summary_result[ 2, c( 1, 3, 4 ) ] ),
  2 ) %>% 
  as.data.frame() %>%
  remove_rownames() %>%
  mutate( model = "mi_model_4",
          sample_size = nrow( mi_dataset ) ) %>%
  rename(
    estimate = "results",
    lower_ci = "(lower",
    upper_ci = "upper)"
  )
results_mi_model_4
```

### 6. Plotting
```{r}
results_all <- bind_rows( 
  results_cc,
  results_mia_nice_model_2,
  results_mia_nice_model_3,
  results_mia_nice_model_4,
  results_mia_ice_model_2,
  results_mia_ice_model_3,
  results_mia_ice_model_4,
  results_mi_model_1,
  results_mi_model_2,
  results_mi_model_3,
  results_mi_model_4 )

writexl::write_xlsx( results_all, "results_all.xlsx" )

#results_all <- read_excel(here("results_all.xlsx"))

results_all <- results_all %>%
  filter( !model %in% c( "mia_nice_model_2", "mia_nice_model_3", "mia_nice_model_4" )  ) %>%
  select( model, estimate, lower_ci, upper_ci, sample_size )

desired_order <- c( "Complete-case analysis", "mi_model_1", 
                    "mi_model_2", "mia_ice_model_2", 
                    "mi_model_3", "mia_ice_model_3",
                    "mi_model_4", "mia_ice_model_4" )
                    
results_all <- results_all %>%
  mutate( model = factor( model, levels = desired_order ) ) %>%
  arrange( model )

results_all <- results_all %>%
  mutate( sample_size = prettyNum( sample_size, big.mark = ",", preserve.width = "none" ) )

results_all <- results_all %>% 
  add_row( model = "Model 1", .before = 2 )

results_all <- results_all %>% 
  add_row( model = "Model 2", .before = 4 )

results_all <- results_all %>% 
  add_row( model = "Model 3", .before = 7 )

results_all <- results_all %>% 
  add_row( model = "Model 4", .before = 10 )

results_all$model[ results_all$model == "Complete-case analysis" ] <- "uCCA"
results_all$model[ results_all$model == "mi_model_1" ] <- paste0( "   ", "MICE" )
results_all$model[ results_all$model == "mi_model_2" ] <- paste0( "   ", "MICE" )
results_all$model[ results_all$model == "mi_model_3" ] <- paste0( "   ", "MICE" )
results_all$model[ results_all$model == "mi_model_4" ] <- paste0( "   ", "MICE" )

# results_all$model[ results_all$model == "mia_nice_model_2" ] <- paste0( "   ", "MIA-NICE" )
# results_all$model[ results_all$model == "mia_nice_model_3" ] <- paste0( "   ", "MIA-NICE" )
# results_all$model[ results_all$model == "mia_nice_model_4" ] <- paste0( "   ", "MIA-NICE" )

results_all$model[ results_all$model == "mia_ice_model_2" ] <- paste0( "   ", "MIA-ICE" )
results_all$model[ results_all$model == "mia_ice_model_3" ] <- paste0( "   ", "MIA-ICE" )
results_all$model[ results_all$model == "mia_ice_model_4" ] <- paste0( "   ", "MIA-ICE" )

results_all <- results_all %>% 
  add_column( "risk_ratio" = paste0(
    sprintf( "%.2f", results_all$estimate ), " (", 
    sprintf( "%.2f", results_all$lower_ci ), ", ", 
    sprintf( "%.2f", results_all$upper_ci ), ")" ),
    .before = 2 )

results_all$risk_ratio <- ifelse( is.na( results_all$estimate ), "", 
                                  results_all$risk_ratio )

results_all$sample_size <- ifelse( is.na( results_all$estimate ), "",
                                   results_all$sample_size )

results_all <- results_all %>% 
  add_column( ` ` = paste( rep( " ", 20 ) , collapse = " " ), .after = 6 )

results_all <- results_all %>%
  add_column( temp1 = " ", .before = 2 ) %>%
  add_column( temp2 = "  ", .before = 7 ) %>%
  add_column( temp3 = "   ", .before = 9 )

names( results_all )[ names( results_all ) %in% c( "model", "temp1", "temp2", "temp3", "risk_ratio", "sample_size" ) ] <- ""

tm <- forest_theme(
  base_size = 11,
  colhead = list( fg_params = list( fontsize = 11 ) ), 
  base_family = "Arial",
  ci_col = "#0072B2"
  )

p_rr <- forest(
  results_all[ , c( 1:3, 7:10 ) ],
  
  est = results_all$estimate,
  lower = results_all$lower_ci,
  upper = results_all$upper_ci,
  
  ci_column = 7,
  sizes = 0.4,
  
  xlim = c( 8, 20 ),
  ticks_at = c( 8, 12, 16, 20 ),
  xlab = "Risk Ratio (95% CI)",
  theme = tm
)

p_rr <- edit_plot( 
  p_rr,
  row = c( 1, 2, 4, 7, 10 ),
  col = 1,
  gp = gpar( fontface = "bold" )
  )

p_rr <- add_text(
  p_rr,
  text = "Model",
  col = 1,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 11,
    fontfamily = "Arial"
  )
)

p_rr <- add_text(
  p_rr,
  text = "(95% CI)",
  col = 3,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 11,
    fontfamily = "Arial"
  )
)

p_rr <- add_text(
  p_rr,
  text = "Size",
  col = 5,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 11,
    fontfamily = "Arial"
  )
)

p_rr <- insert_text(
  p_rr,
  text = "Imputation",
  col = 1,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 11,
    fontfamily = "Arial"
  )
)

p_rr <- add_text(
  p_rr,
  text = "Risk Ratio",
  col = 3,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 11,
    fontfamily = "Arial"
  )
)

p_rr <- add_text(
  p_rr,
  text = "Sample",
  col = 5,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 11,
    fontfamily = "Arial"
  )
)

p_rr <- edit_plot(
  p_rr,
  row = 1:12, 
  which = "background",
  gp = gpar( fill = NA )
  )

p_rr <- add_border(
  p_rr,
  part = "header",
  row = 2,
  col = 1:5,
  where = "bottom",
  gp = gpar( lwd = 1 )
  )

p_rr <- add_border(
  p_rr,
  part = "body",
  row = 1:11,
  col = 1:3,
  where = "bottom",
  gp = gpar( lwd = 1, col = "lightgrey" )
  )

p_rr <- edit_plot(
  p_rr,
  row = c( 6, 9, 12 ),
  col = 7,
  which = "ci",
  gp = gpar(
    col = "red",
    fill = "red"
    )
  )

plot( p_rr )
ggsave( "forest_plot.svg", plot = p_rr, width = 6.5, height = 5 )
```